package bjwxsytx.system.entity;

import java.util.Date;

/**
 * TUserOnline generated by MyEclipse Persistence Tools
 */

public class TUserOnline implements java.io.Serializable {

	// Fields

	private Long id;

	private Long userId;

	private String sessionId;
	
	private String ip;

	private Date loginTime;

	// Constructors

	/** default constructor */
	public TUserOnline() {
	}

	/** full constructor */
	public TUserOnline(Long id, Long userId, String sessionId,String ip,Date loginTime) {
		this.id = id;
		this.userId = userId;
		this.sessionId = sessionId;
		this.ip = ip;
		this.loginTime = loginTime;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TUserOnline [id=");
		builder.append(id);
		builder.append(", userId=");
		builder.append(userId);
		builder.append(", sessionId=");
		builder.append(sessionId);
		builder.append(", ip=");
		builder.append(ip);
		builder.append(", loginTime=");
		builder.append(loginTime);
		builder.append("]");
		return builder.toString();
	}
    
	

	
}