package bjwxsytx.system.entity;

/**
 * SmsPhoneSection generated by MyEclipse Persistence Tools
 */
public class PhoneSection implements java.io.Serializable {

	// Fields
	private Long sectionId;
	private String sectionValue;
	private String areaname;
	
	private String carrier;

	public String getCarrier() {
		return carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	// Constructors
	/** default constructor */
	public PhoneSection() {
	}

	/** minimal constructor */
	public PhoneSection(Long sectionId, String sectionValue) {
		this.sectionId = sectionId;
		this.sectionValue = sectionValue;
	}

	/** full constructor */
	public PhoneSection(Long sectionId, String sectionValue, String areaname,String carrier) {
		this.sectionId = sectionId;
		this.sectionValue = sectionValue;
		this.areaname = areaname;
		this.carrier=carrier;
	}

	// Property accessors
	public Long getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Long sectionId) {
		this.sectionId = sectionId;
	}

	public String getSectionValue() {
		return this.sectionValue;
	}

	public void setSectionValue(String sectionValue) {
		this.sectionValue = sectionValue;
	}

	public String getAreaname() {
		return this.areaname;
	}

	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}
}